// Drafted from the MovieLens catalogue and approved for LLM-judge runs. Not production traffic.
export const judgeQueries = [
  [
    "en-nolan-best",
    "English",
    "director+sort",
    "best christopher nolan movies",
  ],
  [
    "en-hanks-90s",
    "English",
    "actor+genre+years",
    "tom hanks comedies from the 90s",
  ],
  ["en-typo-title", "English", "misspelled-title", "interstelar"],
  [
    "en-scifi-thriller",
    "English",
    "genres+filters",
    "sci-fi thrillers after 2010 with at least 4 stars",
  ],
  ["en-vague-kids", "English", "vague", "a feel-good animated movie for kids"],
  ["en-spielberg-war", "English", "director+genre", "spielberg war films"],
  [
    "en-exclusion",
    "English",
    "unsupported",
    "tarantino movies but not too violent",
  ],
  [
    "en-missing-person",
    "English",
    "missing-entity",
    "salman khan action movies",
  ],
  ["hg-nolan-best", "Hinglish", "director+sort", "nolan ki sabse achhi film"],
  ["hg-aamir", "Hinglish", "person", "aamir khan ki movies dikhao"],
  [
    "hg-dicaprio-after",
    "Hinglish",
    "actor+years",
    "dicaprio ki 2000 ke baad wali filmein",
  ],
  ["hg-vague-horror", "Hinglish", "vague", "koi achhi horror movie batao"],
  [
    "hg-miyazaki-latest",
    "Hinglish",
    "director+sort",
    "miyazaki ki animated filmein latest pehle",
  ],
  ["hg-similar", "Hinglish", "unsupported", "3 idiots jaisi comedy"],
  [
    "hg-two-people",
    "Hinglish",
    "two-people",
    "tom hanks aur spielberg dono wali movies",
  ],
  [
    "hg-typo-person",
    "Hinglish",
    "misspelled-person",
    "irfan khan ki drama films",
  ],
  ["hi-nolan", "Devanagari", "person", "क्रिस्टोफर नोलन की फिल्में"],
  [
    "hi-hanks-comedy",
    "Devanagari",
    "actor+genre",
    "टॉम हैंक्स की कॉमेडी फिल्में",
  ],
  ["hi-dil-se", "Devanagari", "exact-title", "दिल से"],
  [
    "hi-animation-best",
    "Devanagari",
    "genre+years+sort",
    "2015 के बाद की सबसे अच्छी एनिमेशन फिल्में",
  ],
  ["mx-aamir", "Mixed", "person", "aamir khan की फिल्में"],
  ["hi-vague-horror", "Devanagari", "vague", "कोई डरावनी फिल्म दिखाओ"],
  [
    "hi-language",
    "Devanagari",
    "unsupported",
    "हिंदी भाषा की रोमांटिक फिल्में",
  ],
  [
    "hi-dicaprio-before",
    "Devanagari",
    "actor+years",
    "लियोनार्डो डिकैप्रियो की 2010 से पहले की फिल्में",
  ],
].map(([id, script, category, query]) => ({ id, script, category, query }));
